# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
out = "out"
libs = ["node_modules", "lib"]
script = "script"
test = 'test/foundry'
src = 'contracts'
cache_path = 'cache/foundry'
optimize = true
optimizer_runs = 1000
via_ir = true

remappings = [
    'forge-std/=lib/forge-std/src',
    '@openzeppelin/=lib/openzeppelin-contracts',
    '@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable',
    'permit2/=lib/permit2',
    'solmate/=lib/solmate/',
]

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}", url = "https://api.bscscan.com" }
bsc_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.bscscan.com" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org" }
base_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org" }

[rpc_endpoints]
bsc = "https://bsc-dataseed.bnbchain.org"
bsc_testnet = "https://bsc-testnet.bnbchain.org"
base = "https://base.llamarpc.com"
base_testnet = "https://base-sepolia.gateway.tenderly.co"
