# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
out = "out"
libs = ["lib"]
script = "script"
test = 'test'
src = 'contracts'
cache_path = 'cache/foundry'
optimize = true
optimizer_runs = 1
via_ir = true
dynamic_test_linking = true
bytecode_hash = "none"
cbor_metadata = false

fs_permissions = [{ access = "read-write", path = "./broadcast/" }]

remappings = [
    'forge-std/=lib/forge-std/src',
    '@openzeppelin/=lib/openzeppelin-contracts',
    '@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
    'permit2/=lib/permit2',
    'solmate/=lib/solmate/',
]

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}", url = "https://api.bscscan.com" }
bsc_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-testnet.bscscan.com" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org" }
base_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org" }

[rpc_endpoints]
bsc = "https://bsc-dataseed.bnbchain.org"
bsc_testnet = "https://bnb-testnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base.llamarpc.com"
base_testnet = "https://base-sepolia.gateway.tenderly.co"
local = "http://127.0.0.1:8545"
